<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>OpenSH2.Granny2MeshConverter</AssemblyName>
    <RootNamespace>OpenSH2.Granny2MeshConverter</RootNamespace>
  </PropertyGroup>
</Project>
